[versions]
ktx="1.12.0"
hilt="2.48"
androidGradlePlugin = "8.2.2"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
dagger-hilt = {group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }